# Generated by Django 3.2.16 on 2023-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('convesation_id', models.CharField(max_length=100)),
                ('our_phone_number', models.CharField(max_length=100)),
                ('our_phone_number_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('msg_id', models.CharField(max_length=100)),
                ('response_from_user', models.TextField()),
                ('message_type', models.CharField(max_length=100)),
                ('response_from_us', models.TextField()),
                ('New_user_check', models.BooleanField(blank=True, null=True)),
                ('We_responded_check', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
